### ISSUE TITLE
Change CM to launch one data store per app/driver

### ISSUE THREAD

**Issue by Toshbrown** [me-box-archive/databox-netdev#6]

**Comment by yousefamar** [comment]
Anybody on this? If not, please do assign me and I'll set it up. Just to recap, the decisions we've made since before are:
- Stores are single, system-provided containers and have authorization baked in
- Drivers can specify the type of store they require in their manifest
- There are two types; time-series, and document, both with notifications of updates to avoid polling (or hacks like passthrough).
- New stores cannot be launched run-time by drivers, only pre-launch
- If a driver handles multiple data streams that come from one source (e.g. mobile), then they should figure out their own schema for storing that data in a single store (one source → many streams → one driver → one store) and controlling access to individual streams by endpoint through authorization.
- Apps don't get stores (though they can always store internally too), but can read from driver stores they have access to, and write to a special system store for external access

That all correct? Some things we may have touched on slightly, but maybe not decided on, that I would suggest:
- Stores have extra (token-managed) endpoints for exposing their logs to other apps. Depending on how we end up handling the whole config-UI thing, stores probably don't need to host any web stuff, but instead the dashboard could get tokens from the arbiter and query those endpoints to show these logs to the user. Would be useful for debug too.
- In future, instead of launching one store per driver, might we need to give them the option to launch up to one of each type? I.e. a driver could specify in manifest that they need both time-series and document storage. Multiple stores would be for format of data, not multiple streams of data, and could even be seen by apps as a single store, by having different API endpoints resolve to the correct store.

**Comment by Toshbrown** [comment]
I am going to take a look at this on Wednesday. It should not take long.   

I agree with most of the above. However, I thought apps did get stores for publishing/making available processed data that they may output. Apps don't get a store unless it requests one in the manifest.

Also 

Drivers already request their datastore type in the manifest see [databox-driver-wirelessthing](https://github.com/me-box/databox-driver-wirelessthings/blob/master/databox-manifest.json) for an example.

summon @mor1 @haddadi (any comments?)

**Comment by yousefamar** [comment]
> I agree with most of the above. However, I thought apps did get stores for publishing/making available processed data that they may output. Apps don't get a store unless it requests one in the manifest.

Ah, right I forgot about that. And in that case the process is the same, right? So pretty much the only difference between driver and app manifests is in permissions.

**Comment by Toshbrown** [comment]
completed in 145fc07494aa60d8e0040ad36fdfc7eb412688e7
