### ISSUE TITLE
Can someone grant me admin access 

### ISSUE THREAD

**Issue by Toshbrown** [me-box-archive/databox-netdev#8]
I don't have admin access to this repo and need it to set up travis-ci. 

can someone make it so 

Cheers

Tosh

**Comment by yousefamar** [comment]
This repo doesn't have Travis CI on it though, does it? Seems like you can only enable it on forks and public repos you create within me-box. The ones I started before, and transferred to me-box (e.g. this one and `databox-arbiter` etc.) you need admin for to enable.

Did you close this issue after finding a solution? Otherwise, could an organisation admin please go to travis-ci.org and flick the switches for all core components on me-box?
