### ISSUE TITLE
Hypercat compliance

### ISSUE THREAD

**Issue by Toshbrown** [me-box-archive/databox-netdev#9]
The CM should use the /cat endpoint on the arbiter to get the root catalogue. This can then be walked to find all the datastore catalogues which hold sensors and metadata.

**Comment by Toshbrown** [comment]
For information, 

Once the CM and arbiter are started the root Hypercat catalogue is available through the CM proxy via this url: http://127.0.0.1:8989/databox-arbiter/cat

example output:

    {
        "catalogue-metadata": [{
            "rel": "urn:X-hypercat:rels:isContentType",
            "val": "application/vnd.hypercat.catalogue+json"
        }, {
            "rel": "urn:X-hypercat:rels:hasDescription:en",
            "val": "Databox Root Catalogue"
        }, {
            "rel": "urn:X-hypercat:rels:hasHomepage",
            "val": "http://www.databoxproject.uk/"
        }, {
            "rel": "urn:X-hypercat:rels:containsContentType",
            "val": "application/vnd.hypercat.catalogue+json"
        }, {
            "rel": "urn:Xhypercat:rels:supportsSearch",
            "val": "urn:X-hypercat:search:simple"
        }],
        "items": [{
            "item-metadata": [{
                "rel": "urn:X-hypercat:rels:isContentType",
                "val": "application/vnd.hypercat.catalogue+json"
            }, {
                "rel": "urn:X-hypercat:rels:hasDescription:en",
                "val": "databox-driver-twitter-stream-databox-store-blob"
            }],
            "href": "http://databox-driver-twitter-stream-databox-store-blob:8080"
        }]
    }

The 'items' is an array of sub catalogues these can be queried directly using the databoxrequst lib or through the cm proxy:

**direct url:** https://databox-driver-twitter-stream-databox-store-blob:8080/cat
**cm proxy url**: http://127.0.0.1:8989/databox-driver-twitter-stream-databox-store-blob/cat
   
This will return something like this where each 'items' describes an available datasource : 

            {
                "catalogue-metadata":[
                    {
                        "rel":"urn:X-hypercat:rels:isContentType",
                        "val":"application/vnd.hypercat.catalogue+json"
                    },
                    {
                        "rel":"urn:X-hypercat:rels:hasDescription:en",
                        "val":"Databox Datasource Catalogue"
                    },
                    {
                        "rel":"urn:X-hypercat:rels:hasHomepage",
                        "val":"http://www.databoxproject.uk/"
                    },
                    {
                        "rel":"urn:X-hypercat:rels:containsContentType",
                        "val":"application/vnd.hypercat.catalogue+json"
                    },
                    {
                        "rel":"urn:Xhypercat:rels:supportsSearch",
                        "val":"urn:X-hypercat:search:simple"
                    }
                ],
                "items":[
                    {
                        "item-metadata":[
                            {
                                "rel":"urn:X-hypercat:rels:hasDescription:en",
                                "val":"Twitter user timeline data"
                            },
                            {
                                "rel":"urn:X-hypercat:rels:isContentType",
                                "val":"text/json"
                            },
                            {
                                "rel":"urn:X-databox:rels:hasVendor",
                                "val":"databox"
                            },
                            {
                                "rel":"urn:X-databox:rels:hasType",
                                "val":"twitterUserTimeLine"
                            },
                            {
                                "rel":"urn:X-databox:rels:hasLocation",
                                "val":"The Internet"
                            },
                            {
                                "rel":"urn:X-databox:rels:hasDatasourceid",
                                "val":"twitterUserTimeLine"
                            },
                            {
                                "rel":"urn:X-databox:rels:hasStoreType",
                                "val":"databox-store-blob"
                            },
                            {
                                "rel":"urn:X-databox:rels:hasDescription",
                                "val":"Twitter user timeline data"
                            },
                            {
                                "rel":"urn:X-databox:rels:hasUnit",
                                "val":""
                            }
                        ],
                        "href":"https://databox-driver-twitter-stream-databox-store-blob:8080"
                    }
                ]
            }

edit: Updated to the new format

**Comment by yousefamar** [comment]
Excellent! :100:

I'm sorting out https://github.com/me-box/databox-store-blob/issues/21 right now, and was writing tests for store-side hypercat endpoints. In writing validation functions, I was reading through the [specs](http://shop.bsigroup.com/upload/276778/PAS_212.pdf) again, and although they're worded super weirdly, I think 4.3.2 and 4.5.1 are saying that `item-metadata` need to have `urn:X-hypercat:rels:isContentType` in them, with some mime type. (By default could just be `text/plain`, and more structured data as `text/csv`, up to `application/json` etc).

Another thing I was looking at is how the (few) existing implementers of Hypercat (mainly [Thingful](https://thingful.github.io/api-docs/hypercat.html)) name their rels.

Since that's up to the driver though, when the time comes to update https://github.com/me-box/databox-driver-twitter-stream/blob/Hypercat/src/lib/databox-datasource-helper.js#L97, I think we might as well follow the pattern and go:

`urn:X-databox:rels:vendor` →`urn:X-databox:rels:hasVendor`
`urn:X-databox:rels:type` →`urn:X-databox:rels:hasType`
`urn:X-databox:rels:unit` → `urn:X-databox:rels:hasUnit`
`urn:X-databox:rels:location` →`urn:X-databox:rels:hasLocation`
etc.

Also I noticed that [some people](https://github.com/HyperCatIoT/hc2-server/blob/master/server/lib/examples/sensors.json) (outated libs) literally put URLs that link to some naming scheme too, like "http://www.w3.org/2003/01/geo/wgs84_pos#lat" so that's just an interesting possibility too.

Anyway, I'll make tests for validation too, so that can be used as a reference for driver requests.

**Comment by Toshbrown** [comment]
All done see #24
